# Generated by Django 4.1.7 on 2023-03-29 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CurriculumVitate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cv', models.URLField()),
            ],
            options={
                'verbose_name': 'Curriculum Vitate',
            },
        ),
        migrations.CreateModel(
            name='PersonalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('birthday', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('Nationality', models.CharField(max_length=50)),
                ('languages', models.CharField(max_length=150)),
                ('address', models.CharField(max_length=100)),
                ('phone_1', models.CharField(max_length=30)),
                ('phone_2', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Personal Informations',
            },
        ),
        migrations.CreateModel(
            name='ProfilePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_me_photo', models.ImageField(upload_to='Profile Photo')),
            ],
            options={
                'verbose_name': 'Profile Photo',
                'verbose_name_plural': 'Profile Photo',
            },
        ),
    ]
