# Generated by Django 4.1.7 on 2023-03-29 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_info', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='curriculumvitate',
            options={'verbose_name': 'Curriculum Vitate', 'verbose_name_plural': 'Curriculum Vitate'},
        ),
        migrations.AlterModelOptions(
            name='personalinfo',
            options={'verbose_name': 'Personal Information'},
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='phone_2',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
