# Generated by Django 4.1.7 on 2023-03-29 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal_info', '0002_alter_curriculumvitate_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CurriculumVitate',
        ),
    ]
