# Generated by Django 4.1.7 on 2023-03-29 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal_info', '0003_delete_curriculumvitate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalinfo',
            name='birthday',
        ),
    ]
