# Generated by Django 4.1.7 on 2023-03-29 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal_info', '0004_remove_personalinfo_birthday'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personalinfo',
            old_name='Nationality',
            new_name='nationality',
        ),
    ]
