# Generated by Django 4.1.7 on 2023-03-29 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interests', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Interests',
                'verbose_name_plural': 'Interests',
            },
        ),
    ]
