# Generated by Django 4.1.7 on 2023-03-29 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_interests'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=100)),
                ('from_to_and_status', models.CharField(max_length=100)),
                ('institution', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=100)),
                ('from_to_and_status', models.CharField(max_length=200)),
                ('employer', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=200)),
            ],
        ),
    ]
