# Generated by Django 4.1.7 on 2023-03-29 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0004_coursescertifications_projects'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursescertifications',
            options={'verbose_name': 'Courses & Certifications', 'verbose_name_plural': 'Courses & Certifications'},
        ),
        migrations.AlterModelOptions(
            name='projects',
            options={'verbose_name': 'Projects', 'verbose_name_plural': 'Projects'},
        ),
        migrations.RenameField(
            model_name='projects',
            old_name='git_link',
            new_name='github_link',
        ),
    ]
