# Generated by Django 4.1.7 on 2023-03-31 16:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0007_coursescertifications_created_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workexperience',
            name='created_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
