# Generated by Django 4.1.7 on 2023-03-31 16:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0008_workexperience_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='skills',
            name='created_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
